CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE drivers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL CHECK (btrim(first_name) <> ''),
    middle_name TEXT NOT NULL CHECK (btrim(middle_name) <> ''),
    last_name TEXT,
    passport TEXT NOT NULL CHECK (btrim(passport) <> ''),
    CONSTRAINT uk_drivers_passport UNIQUE (passport),
    CONSTRAINT chk_drivers_last_name_not_blank CHECK (last_name IS NULL OR btrim(last_name) <> '')
);

CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT,
    gos_number TEXT NOT NULL CHECK (btrim(gos_number) <> ''),
    tonnage_in_tons NUMERIC(8, 2) NOT NULL CHECK (tonnage_in_tons > 0),
    body_height_in_meters NUMERIC(8, 2) NOT NULL CHECK (body_height_in_meters > 0),
    body_width_in_meters NUMERIC(8, 2) NOT NULL CHECK (body_width_in_meters > 0),
    body_length_in_cubic_meters NUMERIC(8, 2) NOT NULL CHECK (body_length_in_cubic_meters > 0),
    CONSTRAINT uk_vehicles_gos_number UNIQUE (gos_number),
    CONSTRAINT fk_vehicles_driver FOREIGN KEY (driver_id) REFERENCES drivers (id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE retail_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    address TEXT NOT NULL CHECK (btrim(address) <> ''),
    location geometry(Point, 4326) NOT NULL,
    type TEXT NOT NULL,
    timezone TEXT NOT NULL CHECK (btrim(timezone) <> ''),
    CONSTRAINT uk_retail_points_name UNIQUE (name),
    CONSTRAINT uk_retail_points_address UNIQUE (address),
    CONSTRAINT chk_retail_points_timezone CHECK (timezone ~ '^[A-Za-z0-9_./+-]+$')
);

CREATE TABLE routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT,
    creation_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    planned_start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    planned_end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    mileage_in_km NUMERIC(12, 3) NOT NULL CHECK (mileage_in_km > 0),
    CONSTRAINT fk_routes_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT chk_routes_time_window CHECK (planned_end_time >= planned_start_time)
);

CREATE TABLE route_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL,
    retail_point_id BIGINT NOT NULL,
    operation_type TEXT NOT NULL,
    planned_start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    planned_end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    order_number INTEGER NOT NULL CHECK (order_number >= 0),
    CONSTRAINT fk_route_points_route FOREIGN KEY (route_id) REFERENCES routes (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_route_points_retail_point FOREIGN KEY (retail_point_id) REFERENCES retail_points (id) ON UPDATE CASCADE,
    CONSTRAINT uk_route_points_route_order UNIQUE (route_id, order_number),
    CONSTRAINT chk_route_points_time_window CHECK (planned_end_time >= planned_start_time)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_point_id BIGINT NOT NULL,
    goods_type TEXT NOT NULL CHECK (btrim(goods_type) <> ''),
    min_temperature INTEGER,
    max_temperature INTEGER,
    volume_in_cubic_meters NUMERIC(12, 3) NOT NULL CHECK (volume_in_cubic_meters > 0),
    weight_in_kg NUMERIC(12, 3) NOT NULL CHECK (weight_in_kg > 0),
    CONSTRAINT fk_orders_route_point FOREIGN KEY (route_point_id) REFERENCES route_points (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_orders_temperature CHECK (min_temperature IS NULL OR max_temperature IS NULL OR max_temperature >= min_temperature)
);

ALTER TABLE retail_points
    ADD CONSTRAINT chk_retail_points_type
    CHECK (type IN ('SHOP', 'WAREHOUSE', 'GARAGE'));

ALTER TABLE route_points
    ADD CONSTRAINT chk_route_points_operation_type
    CHECK (operation_type IN ('LOAD', 'UNLOAD', 'VISIT'));

CREATE INDEX idx_routes_vehicle ON routes (vehicle_id);
CREATE INDEX idx_routes_planned_start ON routes (planned_start_time);
CREATE INDEX idx_route_points_route ON route_points (route_id);
CREATE INDEX idx_route_points_retail ON route_points (retail_point_id);
CREATE INDEX idx_orders_route_point ON orders (route_point_id);
CREATE INDEX idx_retail_points_location ON retail_points USING GIST (location);
